### ISSUE TITLE
ControllerState is missing use_item for Rumble-like game modes

### ISSUE THREAD

**Issue by NicEastvillage** [RLBot/rlbot-rust#15]
This field <https://github.com/RLBot/RLBot/blob/master/src/main/flatbuffers/rlbot.fbs#L30> is missing from the ControllerState struct.

**Comment by naturecodevoid** [comment]
#16 would close this.

**Comment by Quetzal2** [comment]
Since #16 has been merged, the field is now part of ControllerState (73408649ca466d58abf444956ab1aa12207974cc).
Can we consider this issue closed?

**Comment by NicEastvillage** [comment]
Yes!
